### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ghost** [HadesVR/HadesVR#2]
Hello I hope you are doing well! 

I am very interested into this project and I was wondering if this was compatible with linux or if it isn't if its on your roadmap.

Kind regards

**Comment by FreddyFeuerstein** [comment]
I mean its written in c, its open source, its documented, just try to compile it and see what happens. If it throws errors then you gotta change a few things in terms of io control

**Comment by LiquidCGS** [comment]
I'm pretty late here but no, I don't have linux support planned. Steamvr's openvr api is absolute trash in linux, and I personally don't feel like messing with the nuances that brings. Maybe in the future?, not the near future that's for sure.
Also PSMoveServiceEX doesn't work on linux afaik, so even if you did get the driver working you'd only have 3dof tracking.

So if you want a driver with linux support I recommend checking hobo_vr Okawo has been working on linux support for it:
https://github.com/HoboVR-Labs/hobo_vr

I'm gonna quote the hobo_vr readme:
"Linux support is a huge concern, however it is not made easy by the absent openvr_driver API documentation not to mention the blatant disparities in the API functionality between platforms with no explanation what so ever, bugs, dead interfaces, undocumented interfaces, etc. working with openvr_driver API especially on Linux is downright repulsive!"

Cheers.

**Comment by iAmInActions** [comment]
> So if you want a driver with linux support I recommend checking hobo_vr Okawo has been working on linux support for it: https://github.com/HoboVR-Labs/hobo_vr

Thanks this is just what i searched for. Gonna implement some sort of TVR thing similar to driver4vr under linux for playing vr games on my pc.
