### ISSUE TITLE
"mpu" question 

### ISSUE THREAD

**Issue by LabrentFiero** [HadesVR/HadesVR#9]
Hello. I don't have an mpu9250. Can I use mpu6050 without magnetometer in your project?

**Comment by LiquidCGS** [comment]
You can but with the current driver version you'll get yaw drift over time so you'll have to keep recentering your view every now and then, either by pressing f8 or with the controllers if you build them.

I'm working on something to eliminate the need for an IMU wtih a magnetometer but it's still very experimental. I plan to have it out by next driver release.
